"""
Blaze WAF Detector - Comprehensive Web Application Firewall detection.
Detects 20+ WAF/CDN providers through header analysis, cookie inspection,
body pattern matching, and behavioral analysis.
"""

import re
from dataclasses import dataclass, field
from typing import Dict, List, Optional


@dataclass
class WAFResult:
    detected: bool = False
    waf_names: List[str] = field(default_factory=list)
    confidence: Dict[str, float] = field(default_factory=dict)
    details: Dict[str, str] = field(default_factory=dict)

    def add(self, name: str, confidence: float, detail: str = ""):
        if name not in self.waf_names:
            self.waf_names.append(name)
        self.confidence[name] = max(self.confidence.get(name, 0), confidence)
        if detail:
            self.details[name] = detail
        self.detected = True

    def merge(self, other: "WAFResult"):
        for name in other.waf_names:
            self.add(
                name,
                other.confidence.get(name, 0.5),
                other.details.get(name, ""),
            )


# ──────────────────────────── Signature Database ────────────────────────────

WAF_SIGNATURES = {
    "Cloudflare": {
        "headers": {
            "cf-ray": r".*",
            "cf-cache-status": r".*",
            "cf-request-id": r".*",
            "server": r"(?i)cloudflare",
            "cf-mitigated": r".*",
        },
        "cookies": [r"__cfduid", r"__cf_bm", r"cf_clearance"],
        "body": [
            r"Attention Required! \| Cloudflare",
            r"cf-error-details",
            r"cloudflare\.com/5xx-error-landing",
            r"DDoS protection by Cloudflare",
            r"ray ID:",
            r"Checking your browser before accessing",
            r"Enable JavaScript and cookies to continue",
            r"performance &amp; security by Cloudflare",
        ],
        "status_codes": [403, 503, 1020],
    },
    "Akamai": {
        "headers": {
            "x-akamai-transformed": r".*",
            "akamai-grn": r".*",
            "x-akamai-session-info": r".*",
            "server": r"(?i)AkamaiGHost|AkamaiNetStorage",
            "x-akamai-request-id": r".*",
        },
        "cookies": [r"akamai_", r"ak_bmsc", r"bm_sv", r"_abck"],
        "body": [
            r"Access Denied",
            r"Reference\s*#\d+\.\w+\.\d+",
            r"AkamaiGHost",
            r"akamaiedge\.net",
            r"Your access to .* has been blocked",
        ],
        "status_codes": [403],
    },
    "Imperva/Incapsula": {
        "headers": {
            "x-cdn": r"(?i)Incapsula|Imperva",
            "x-iinfo": r".*",
            "x-cdn-forward": r".*",
        },
        "cookies": [
            r"visid_incap_\d+",
            r"incap_ses_\d+",
            r"nlbi_\d+",
            r"___utmvc",
        ],
        "body": [
            r"Incapsula incident ID",
            r"Powered By Incapsula",
            r"_Incapsula_Resource",
            r"Request unsuccessful\. Incapsula",
            r"imperva\.com",
        ],
        "status_codes": [403],
    },
    "AWS WAF": {
        "headers": {
            "x-amzn-requestid": r".*",
            "x-amz-cf-id": r".*",
            "x-amz-id-2": r".*",
            "server": r"(?i)awselb|amazon|CloudFront",
            "x-amz-apigw-id": r".*",
        },
        "cookies": [r"AWSALB", r"AWSALBCORS", r"aws-waf-token"],
        "body": [
            r"<html><head><title>ERROR: The request could not be satisfied</title>",
            r"Request blocked",
            r"Generated by cloudfront",
            r"AWS WAF",
        ],
        "status_codes": [403],
    },
    "Sucuri": {
        "headers": {
            "x-sucuri-id": r".*",
            "x-sucuri-cache": r".*",
            "server": r"(?i)Sucuri|Cloudproxy",
            "x-sucuri-block": r".*",
        },
        "cookies": [r"sucuri_cloudproxy"],
        "body": [
            r"Access Denied - Sucuri Website Firewall",
            r"sucuri\.net/privacy-policy",
            r"Sucuri WebSite Firewall",
            r"CloudProxy",
            r"If you are the site owner",
        ],
        "status_codes": [403],
    },
    "ModSecurity": {
        "headers": {
            "server": r"(?i)mod_security|NOYB",
        },
        "cookies": [],
        "body": [
            r"ModSecurity",
            r"This error was generated by Mod_Security",
            r"Not Acceptable!.*mod_security",
            r"ModSecurity Action",
            r"mod_security",
            r"NOYB",
        ],
        "status_codes": [403, 406],
    },
    "F5 BIG-IP ASM": {
        "headers": {
            "x-wa-info": r".*",
            "server": r"(?i)BIG-?IP|BigIP",
            "x-cnection": r".*",
        },
        "cookies": [r"BIGipServer", r"TS\w{6,}", r"f5_cspm", r"MRHSession"],
        "body": [
            r"The requested URL was rejected",
            r"Please consult with your administrator",
            r"Your support ID is",
            r"F5 Networks",
        ],
        "status_codes": [403],
    },
    "Barracuda": {
        "headers": {
            "server": r"(?i)Barracuda",
        },
        "cookies": [r"barra_counter_session", r"BNI__BARRACUDA_LB_COOKIE"],
        "body": [
            r"Barracuda Web Application Firewall",
            r"You have been blocked",
            r"barra_counter_session",
        ],
        "status_codes": [403],
    },
    "Wordfence": {
        "headers": {},
        "cookies": [r"wfvt_\d+", r"wordfence_verifiedHuman"],
        "body": [
            r"Generated by Wordfence",
            r"This response was generated by Wordfence",
            r"Your access to this site has been limited",
            r"wordfence",
            r"wfAction=blocked",
            r"Wordfence Security",
        ],
        "status_codes": [403, 503],
    },
    "Fortinet/FortiWeb": {
        "headers": {
            "server": r"(?i)FortiWeb",
            "fortiwafsid": r".*",
        },
        "cookies": [r"FORTIWAFSID", r"cookiesession1"],
        "body": [
            r"FortiWeb",
            r"\.fwebErrorPage",
            r"Web Page Blocked",
            r"fortigate",
        ],
        "status_codes": [403],
    },
    "Citrix NetScaler/ADC": {
        "headers": {
            "cneonction": r".*",
            "via": r"(?i)NS-CACHE",
            "x-ns-cache": r".*",
        },
        "cookies": [r"ns_af", r"citrix_ns_id", r"NSC_"],
        "body": [
            r"NS Transaction",
            r"Citrix",
            r"Access Gateway",
            r"ns_af",
        ],
        "status_codes": [403],
    },
    "DenyAll": {
        "headers": {},
        "cookies": [r"sessioncookie", r"da_session"],
        "body": [
            r"Condition Intercepted",
            r"DenyAll",
        ],
        "status_codes": [403],
    },
    "SonicWall": {
        "headers": {
            "server": r"(?i)SonicWALL",
        },
        "cookies": [],
        "body": [
            r"This request is blocked by the SonicWall",
            r"Web Site Blocked",
            r"nsa_banner",
        ],
        "status_codes": [403],
    },
    "Comodo WAF": {
        "headers": {
            "server": r"(?i)Protected by COMODO",
        },
        "cookies": [],
        "body": [
            r"Protected by COMODO WAF",
            r"COMODO Web Application Firewall",
        ],
        "status_codes": [403],
    },
    "Wallarm": {
        "headers": {
            "server": r"(?i)nginx-wallarm",
        },
        "cookies": [],
        "body": [
            r"wallarm",
            r"nginx-wallarm",
        ],
        "status_codes": [403],
    },
    "Radware/AppWall": {
        "headers": {
            "x-sl-compstate": r".*",
        },
        "cookies": [],
        "body": [
            r"Unauthorized Activity Has Been Detected",
            r"Radware",
            r"AppWall",
        ],
        "status_codes": [403],
    },
    "StackPath": {
        "headers": {
            "x-sp-": r".*",
            "server": r"(?i)StackPath",
        },
        "cookies": [],
        "body": [
            r"StackPath",
            r"You performed an action that triggered the service",
        ],
        "status_codes": [403],
    },
    "Edgecast/Verizon": {
        "headers": {
            "server": r"(?i)ECD|ECS",
            "x-ec-custom-error": r".*",
        },
        "cookies": [],
        "body": [
            r"Please retry your request",
            r"Verizon Digital Media",
        ],
        "status_codes": [403],
    },
    "Reblaze": {
        "headers": {
            "server": r"(?i)Reblaze Secure Web Gateway",
            "x-rb-": r".*",
        },
        "cookies": [r"rbzid", r"rbzsessionid"],
        "body": [
            r"Access Denied.*Reblaze",
            r"Reblaze",
        ],
        "status_codes": [403],
    },
    "Armor Defense": {
        "headers": {
            "server": r"(?i)Armor",
        },
        "cookies": [],
        "body": [
            r"blocked by website protection from Armor",
            r"Armor Defense",
        ],
        "status_codes": [403],
    },
    "Alibaba Cloud WAF": {
        "headers": {
            "server": r"(?i)Tengine|ASERVER",
            "eagleid": r".*",
        },
        "cookies": [r"aliyungf_tc"],
        "body": [
            r"errors\.aliyun\.com",
            r"Sorry, your request has been blocked",
        ],
        "status_codes": [405, 403],
    },
    "Palo Alto": {
        "headers": {},
        "cookies": [],
        "body": [
            r"has been blocked in accordance with company policy",
            r"Palo Alto Next Generation Security Platform",
        ],
        "status_codes": [403],
    },
}

# Which WAFs should trigger an automatic stop recommendation
CRITICAL_WAFS = {
    "Cloudflare",
    "Akamai",
    "Imperva/Incapsula",
    "AWS WAF",
    "F5 BIG-IP ASM",
}


class WAFDetector:
    def __init__(self):
        self.signatures = WAF_SIGNATURES
        self.critical_wafs = CRITICAL_WAFS

    def detect(
        self, headers: Dict, body: str, cookies: Dict
    ) -> WAFResult:
        result = WAFResult()

        for waf_name, sigs in self.signatures.items():
            confidence = 0.0
            detail_parts = []

            # Check headers
            for header_name, pattern in sigs.get("headers", {}).items():
                for resp_header, resp_value in headers.items():
                    if resp_header.lower() == header_name.lower():
                        if re.search(pattern, str(resp_value)):
                            confidence += 0.4
                            detail_parts.append(
                                f"Header: {resp_header}={resp_value}"
                            )

            # Check cookies
            cookie_str = " ".join(
                f"{k}={v}" for k, v in cookies.items()
            )
            all_cookies = list(cookies.keys())
            for cookie_pattern in sigs.get("cookies", []):
                for cookie_name in all_cookies:
                    if re.search(cookie_pattern, cookie_name, re.IGNORECASE):
                        confidence += 0.3
                        detail_parts.append(f"Cookie: {cookie_name}")

            # Check body patterns
            for body_pattern in sigs.get("body", []):
                if re.search(body_pattern, body, re.IGNORECASE):
                    confidence += 0.5
                    detail_parts.append(f"Body pattern: {body_pattern[:50]}")

            if confidence >= 0.3:
                result.add(
                    waf_name,
                    min(confidence, 1.0),
                    "; ".join(detail_parts[:3]),
                )

        return result

    def is_waf_block(
        self, status_code: int, headers: Dict, body: str
    ) -> bool:
        """Quick check if a response looks like a WAF block (used during scanning)."""
        if status_code not in (403, 406, 429, 503, 1020):
            return False

        block_indicators = [
            r"Access Denied",
            r"Request blocked",
            r"Forbidden",
            r"blocked by",
            r"security policy",
            r"web application firewall",
            r"rate limit",
            r"too many requests",
            r"Your IP",
            r"has been blocked",
            r"DDoS protection",
            r"Checking your browser",
            r"challenge-platform",
        ]

        for pattern in block_indicators:
            if re.search(pattern, body, re.IGNORECASE):
                return True

        # Check specific WAF headers
        waf_headers = [
            "cf-ray",
            "x-sucuri-id",
            "x-akamai-transformed",
            "x-iinfo",
        ]
        for h in waf_headers:
            if h in {k.lower() for k in headers.keys()}:
                if status_code in (403, 503):
                    return True

        return False

    def is_critical(self, waf_result: WAFResult) -> bool:
        """Check if detected WAFs include critical ones that should stop scanning."""
        return any(
            name in self.critical_wafs for name in waf_result.waf_names
        )
